version: "3.8"
services:
  #apache2
  apache2:
    container_name: apache2
    build: ./docker/apache2
    ports:
      - "8000:80"
    volumes:
      - ./docker/apache2/vhosts:/etc/apache2/sites-enabled
      - ./app:/var/www
      - ./var/logs/apache2:/var/log/apache2 # apache_logs
      - ./docker/apache2/files:/home/badges-access/files
    restart: always
    networks:
      - network
  #Base de donn√©es MariaDB
  db:
    container_name: db
    image: mariadb:10.5.8
    restart: always
    volumes:
      - ./var/db-data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      TZ: Europe/Paris
    networks:
      - network
  #PHP My Admin
  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - network
  ##Attack-box
  attack-box:
    container_name: attack-box
    build: ./docker/attack-box
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=100O
      - PGID=1000
      - TZ=Europe/Paris
      #- SUBFOLDER=/ #optional
      - TITLE=Edu OWASP Attack Box #optional
    volumes:
      - ./var/config:/config
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - '3000:3000'
      - '3001:3001'
      - '9001:9001'
    #    devices:
    #      - /dev/dri:/dev/dri #optional
    shm_size: "4gb" #optional
    restart: unless-stopped
    networks:
      - network
  #Malicious scripts library
  evil-storage:
    container_name: evil-storage
    image: php:8.2-apache
    ports:
      - "9002:80"
    volumes:
      - ./docker/evil-storage:/var/www/html
      - ./var/logs/evil-storage:/var/log/apache2 # apache_logs
    restart: always
    networks:
      - network
#Network
networks:
  network:
#Volumes
#volumes:
#  db-data:
#  log: